#!/bin/bash

echo "Installing Omada Cloud by JOSE CAPP"

echo "Updating apt package"
sudo apt-get -y update 

echo "installing mongodb"
sudo apt-get -y install mongodb

echo "installling jsvc"
sudo apt-get -y install jsvc

echo "installing openjdk-8-jdk"
sudo apt-get -y install openjdk-8-jdk

echo "this will update config java. please select 2"
sudo update-alternatives --config java

echo "installing gdebi-core"
sudo apt-get -y install gdebi-core

echo "downloading omada sdn controller"
cd

#sudo wget -O https://firebasestorage.googleapis.com/v0/b/upgradeteamtech.appspot.com/o/LATEST%2FOmada_SDN_Controller_v5.14.32.3_linux_x64.deb?alt=media&token=0bab9726-180c-4906-bf12-0d7020bd4025"
sudo wget https://static.tp-link.com/upload/software/2024/202411/20241101/Omada_SDN_Controller_v5.14.32.3_linux_x64.deb

echo "now installing sdn controller"
cd
#sudo -i gdebi -n Omada_SDN_Controller_v5.14.32.3_linux_x64.deb

sudo -i gdebi -n Omada_SDN_Controller_v5.14.32.3_linux_x64.deb
