#!/bin/bash

echo "Installing Omada Cloud by Arclem"

echo "Updating apt package"
sudo apt-get -y update 

echo "installing mongodb"
sudo apt-get -y install mongodb

echo "installling jsvc"
sudo apt-get -y install jsvc

echo "installing openjdk-8-jdk"
sudo apt-get -y install openjdk-8-jdk

echo "this will update config java. please select 2"
sudo update-alternatives --config java

echo "installing gdebi-core"
sudo apt-get -y install gdebi-core

echo "downloading omada sdn controller"
cd

#sudo wget -O Omada_SDN_Controller_v5.14.26.1_linux_x64.deb "https://firebasestorage.googleapis.com/v0/b/omada-efef8.appspot.com/o/Omada_SDN_Controller_v5.14.26.1_linux_x64.deb?alt=media&token=c8220ffe-6e09-4ea2-866a-58f63b26620f"

sudo wget https://static.tp-link.com/upload/software/2024/202407/20240710/Omada_SDN_Controller_v5.14.26.1_linux_x64.deb


echo "now installing sdn controller"
cd
#sudo -i gdebi -n Omada_SDN_Controller_v5.14.26.1_linux_x64.deb

sudo -i gdebi -n Omada_SDN_Controller_v5.14.26.1_linux_x64.deb


