#!/bin/bash

echo "Installing Omada Cloud by TEAM-TECH JOSE"

echo "Updating apt package"
sudo apt-get -y update 

echo "installing mongodb"
sudo apt-get -y install mongodb

echo "installling jsvc"
sudo apt-get -y install jsvc

echo "installing openjdk-8-jdk"
sudo apt-get -y install openjdk-8-jdk

echo "this will update config java. please select 2"
sudo update-alternatives --config java

echo "installing gdebi-core"
sudo apt-get -y install gdebi-core

echo "downloading omada sdn controller"
cd

#sudo wget -O Omada_SDN_Controller_v5.13.22_Linux_x64.deb
"https://firebasestorage.googleapis.com/v0/b/upgradeteamtech.appspot.com/o/UPGRADE%2FOmada_SDN_Controller_v5.13.22_Linux_x64.deb?alt=media&token=fefe6914-cf4e-44cc-aa08-e3a48bdcffb9"

sudo wget https://static.tp-link.com/upload/software/2023/202312/20231201/Omada_SDN_Controller_v5.13.22_Linux_x64.deb


echo "now installing sdn controller"
cd
#sudo -i gdebi -n Omada_SDN_Controller_v5.13.22_Linux_x64.deb

sudo -i gdebi -n Omada_SDN_Controller_v5.13.22_Linux_x64.deb
