#!/bin/bash

echo "Installing Omada Cloud by TEAM-TECH JOSE"

echo "Updating apt package"
sudo apt-get -y update 

echo "installing mongodb"
sudo apt-get -y install mongodb

echo "installling jsvc"
sudo apt-get -y install jsvc

echo "installing openjdk-8-jdk"
sudo apt-get -y install openjdk-8-jdk

echo "this will update config java. please select 2"
sudo update-alternatives --config java

echo "installing gdebi-core"
sudo apt-get -y install gdebi-core

echo "downloading omada sdn controller"
cd

#sudo wget -O Omada_SDN_Controller_v5.13.30.8_linux_x64.deb
"https://firebasestorage.googleapis.com/v0/b/omadaskywalker.appspot.com/o/Omada_SDN_Controller_v5.13.30.8_linux_x64.deb?alt=media&token=e515d71e-f7dd-45d1-b5eb-31dc1c08584b"

sudo wget https://static.tp-link.com/upload/software/2024/202402/20240227/Omada_SDN_Controller_v5.13.30.8_linux_x64.deb


echo "now installing sdn controller"
cd
#sudo -i gdebi -n Omada_SDN_Controller_v5.13.30.8_linux_x64.deb

sudo -i gdebi -n Omada_SDN_Controller_v5.13.30.8_linux_x64.deb
